service:
  name: ownstats-${self:custom.sanitizedDomainName}

plugins:
  - serverless-pseudo-parameters
  - serverless-plugin-existing-s3
  - serverless-stack-output
  - serverless-s3-sync
  - serverless-cloudfront-invalidate

custom:

  # Store the domain name, otherwise use default
  domainName: ${opt:domain}
  sanitizedDomainName: ${file(./modules/sanitize.js):sanitizeDomainName}

  # Output plugin configuration
  output:
    handler: modules/renderScript.handler

  # S3 buckets
  s3:
    buckets:
      logs: ${self:service.name}-logs
      distribution: ${self:service.name}

  # Glue database name
  glue:
    database: ${file(./modules/sanitize.js):sanitizeDatabaseName}
    tables:
      raw: access_logs_raw
      optimized: access_logs

  # Prefixes
  prefixes:
    incoming: incoming/
    partitionedGz: partitioned-gz/
    partitionedParquet: partitioned-parquet/
    athenaQueryResults: athena-query-results/

  # For caching with CloudFront in general, see
  # https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/Expiration.html#ExpirationDownloadDist

  # CloudFront invalidation plugin configuration
  cloudfrontInvalidate:
    distributionIdKey: 'CloudFrontDistributionId'
    items: # Add your files to invalidate here:
      - '/script.js'

  # S3 sync plugin configuration
  s3Sync:
    - bucketName: ${self:service.name}
      localDir: src

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'us-east-1'}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - athena:StartQueryExecution
        - athena:GetQueryExecution
      Resource: '*'
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetBucketLocation
        - s3:GetBucketNotification
        - s3:PutBucketNotification
      Resource: 'arn:aws:s3:::${self:custom.s3.buckets.logs}'
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
        - s3:DeleteObject
      Resource: 'arn:aws:s3:::${self:custom.s3.buckets.logs}/*'
    - Effect: Allow
      Action:
        - glue:CreatePartition
        - glue:GetDatabase
        - glue:GetTable
        - glue:BatchCreatePartition
        - glue:GetPartition
        - glue:GetPartitions
        - glue:CreateTable
        - glue:DeleteTable
        - glue:DeletePartition
      Resource: '*'

functions:
  transformPartition:
    handler: functions/transformPartition.handler
    description: 'Transform Athena partitions'
    memorySize: 256
    timeout: 900
    environment:
      SOURCE_TABLE: '#{PartitionedGzTable}'
      TARGET_TABLE: '#{PartitionedParquetTable}'
      DATABASE: '#{AccessLogsDatabase}'
      ATHENA_QUERY_RESULTS_LOCATION: 's3://#{LogBucket}/${self:custom.prefixes.athenaQueryResults}'
      ATHENA_CTAS_RESULTS_LOCATION: 's3://#{LogBucket}/${self:custom.prefixes.partitionedParquet}'
      S3_BUCKET: '#{LogBucket}'
      S3_PREFIX: '${self:custom.prefixes.partitionedGz}'
      LOG_LEVEL: debug
    events:
      - schedule: cron(1 * * * ? *)
  createPartition:
    handler: functions/createPartition.handler
    description: 'Create Athena partitions'
    memorySize: 256
    timeout: 10
    environment:
      TABLE: '#{PartitionedGzTable}'
      DATABASE: '#{AccessLogsDatabase}'
      ATHENA_QUERY_RESULTS_LOCATION: 's3://#{LogBucket}/${self:custom.prefixes.athenaQueryResults}'
      LOG_LEVEL: debug
    events:
      - schedule: cron(55 * * * ? *)
  moveAccessLogs:
    handler: functions/moveAccessLogs.handler
    description: 'Move incoming files to partitioned prefix structure'
    memorySize: 256
    timeout: 30
    environment:
      TARGET_KEY_PREFIX: '${self:custom.prefixes.partitionedGz}'
      LOG_LEVEL: debug
    events:
      - existingS3:
          bucket: ${self:custom.s3.buckets.logs}
          events: 
            - s3:ObjectCreated:*
          rules:
            - prefix: '${self:custom.prefixes.incoming}'

package:
  include:
    - function/**
  exclude:
    - resources/**
    - modules/**
    - src/**
    - .gitignore
    - LICENSE
    - package.json
    - package-lock.json
    - README.md

resources:

  - ${file(resources/cloudfront-origin-access-identity.yml)}
  - ${file(resources/s3-buckets.yml)}
  - ${file(resources/s3-policies.yml)}
  - ${file(resources/cf-distribution.yml)}
  - ${file(resources/glue-db.yml)}
  - ${file(resources/glue-table-partitioned-gz.yml)}
  - ${file(resources/glue-table-partitioned-parquet.yml)}
  - ${file(resources/outputs.yml)}
