Resources:
  PartitionedParquetTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: '#{AWS::AccountId}'
      DatabaseName: '#{AccessLogsDatabase}'
      TableInput:
        Name: '${self:custom.glue.tables.optimized}'
        Description: 'Parquet format access logs as transformed from gzip version'
        TableType: EXTERNAL_TABLE
        Parameters: { 'has_encrypted_data': 'false', 'parquet.compression': 'SNAPPY' }
        PartitionKeys:
        - Name: year
          Type: string
        - Name: month
          Type: string
        - Name: day
          Type: string
        - Name: hour
          Type: string
        StorageDescriptor:
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          Columns:
          - Name: date
            Type: date
          - Name: time
            Type: string
          - Name: location
            Type: string
          - Name: bytes
            Type: bigint
          - Name: requestip
            Type: string
          - Name: method
            Type: string
          - Name: host
            Type: string
          - Name: uri
            Type: string
          - Name: status
            Type: int
          - Name: referrer
            Type: string
          - Name: useragent
            Type: string
          - Name: querystring
            Type: string
          - Name: cookie
            Type: string
          - Name: resulttype
            Type: string
          - Name: requestid
            Type: string
          - Name: hostheader
            Type: string
          - Name: requestprotocol
            Type: string
          - Name: requestbytes
            Type: bigint
          - Name: timetaken
            Type: float
          - Name: xforwardedfor
            Type: string
          - Name: sslprotocol
            Type: string
          - Name: sslcipher
            Type: string
          - Name: responseresulttype
            Type: string
          - Name: httpversion
            Type: string
          - Name: filestatus
            Type: string
          - Name: encryptedfields
            Type: string
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          Location: 's3://#{LogBucket}/${self:custom.prefixes.partitionedParquet}'
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
