Resources:
  DistributionBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.s3.buckets.distribution}
  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.s3.buckets.logs}
      #PublicAccessBlockConfiguration:
        #BlockPublicAcls: 'true'
        #BlockPublicPolicy: 'true'
        #IgnorePublicAcls: 'true'
        #RestrictPublicBuckets: 'true'
