Resources:
  DistributionBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.s3.buckets.distribution}
  LogBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: ${self:custom.s3.buckets.logs}
